import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <main className="h-screen mx-32 border-solid border-white border">
      <h1 className="text-3xl text-yellow-700 font-bold underline border-solid border-white border mt-28">
      Hello world!
      </h1>
      </main>
      

      <footer className={styles.footer}>
    

          <span>
            <Image src="/logo_graphic_transparent.png" alt="Dot Vonn Logo" width='150%' height='150%'/>
          </span>
        
      </footer>
    </div>
  )
}
